kind: pipeline
type: docker
name: default

steps:
  # - name: lint
  #   image: node:20
  #   commands:
  #     - npm install
  #     - npm run lint

  # - name: deploy
  #   image: appleboy/drone-ssh
  #   settings:
  #     host: 45.153.69.201
  #     username: root
  #     password: o9_+U8s8JVPjNZ
  #     port: 22
  #     script:
  #       - cd /root/studio
  #       - source ~/.nvm/nvm.sh
  #       - nvm use 22
  #       - git pull origin master
  #       - npm install
  #       - npm run build
  #       - pm2 restart your-app-name

  - name: notify
    image: appleboy/drone-telegram:1.3.10
    settings:
      token:
        from_secret: telegram_token
      to: -4551183176
      message: |
        ✅ Успешно развернуто приложение после коммита на ветке master!

        Коммит: {{ .Commit }}
        Сообщение коммита: {{ .CommitMessage }}

trigger:
  event:
    - push
