# kind: pipeline
# type: docker
# name: default

# steps:
#   # - name: lint
#   #   image: node:20
#   #   commands:
#   #     - npm ci
#   #     - npm run lint

#   - name: deploy
#     image: appleboy/drone-ssh
#     settings:
#       host:
#         from_secret: host
#       username:
#         from_secret: username
#       password:
#         from_secret: password
#       port:
#         from_secret: port
#       script:
#         - cd /root/studio
#         - source ~/.nvm/nvm.sh
#         - nvm use 22
#         - git pull origin master
#         - npm ci
#         - npm run build
#         - pm2 restart your-app-name

#   - name: notify
#     image: appleboy/drone-telegram:1.3.10
#     settings:
#       token:
#         from_secret: telegram_token
#       to: -4551183176
#       message: |
#         ✅ Успешно развернуто приложение после коммита на ветке master!

# trigger:
#   branch:
#     - master
#   event:
#     - push

kind: pipeline
type: docker
name: default

steps:
  - name: lint
    image: node:20
    commands:
      - npm install
      - npm run lint

trigger:
  event:
    - push
    - pull_request
    - tag
    - branch
    - deployment
