kind: pipeline
type: docker
name: default

steps:
  # - name: lint
  #   image: node:20
  #   commands:
  #     - npm install
  #     - npm run lint

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 45.153.69.201
      username: root
      password: o9_+U8s8JVPjNZ
      port: 22
      script:
        - cd /root/studio
        - source ~/.nvm/nvm.sh
        - nvm use 22
        - git pull origin master
        - npm install
        - npm run build
        - pm2 restart your-app-name

  - name: notify
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: 7667848651:AAFC29EEL9jkm6c6CoXZ-XWN0JZ_dh7hhuE
      chat_id:
        from_secret: -4551183176
      message: "✅ Успешно развернуто приложение после коммита на ветке master!"

trigger:
  event:
    - push
