# version: "3"

# services:
#   drone-server:
#     image: drone/drone:2
#     container_name: drone-server
#     ports:
#       - 8080:80
#     volumes:
#       - /var/lib/drone:/data
#     restart: always
#     environment:
#       - DRONE_GITHUB_SERVER=https://github.com
#       - DRONE_GITHUB_CLIENT_ID=Ov23liuw92ndgEPaj1vU
#       - DRONE_GITHUB_CLIENT_SECRET=f73ec67795e34f4495994b43e7cd6342fd241921
#       - DRONE_RPC_SECRET=your_rpc_secret
#       - DRONE_SERVER_HOST=https://drone.barbarisstudio.ru
#       - DRONE_SERVER_PROTO=https

#   drone-runner:
#     image: drone/drone-runner-docker:1
#     container_name: drone-runner
#     restart: always
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#     environment:
#       - DRONE_RPC_HOST=drone-server:80
#       - DRONE_RPC_SECRET=your_rpc_secret
#       - DRONE_RUNNER_CAPACITY=2
#       - DRONE_RUNNER_NAME=runner

#       - DRONE_SERVER_HOST=drone.barbarisstudio.ru
#       - DRONE_SERVER_PROTO=https

version: "3"

services:
  drone-server:
    image: drone/drone:2
    container_name: drone-server
    ports:
      - 8080:80
    volumes:
      - /var/lib/drone:/data
    restart: always
    environment:
      - DRONE_GITHUB_SERVER=https://github.com
      - DRONE_GITHUB_CLIENT_ID=Ov23li8wnqPBYijzNCjz
      - DRONE_GITHUB_CLIENT_SECRET=d78d2d6ba9bc1022fcb007c3ca85a3349823cf8e
      - DRONE_RPC_SECRET=your_rpc_secret
      - DRONE_SERVER_HOST=drone.barbarisstudio.ru
      - DRONE_SERVER_PROTO=https

  drone-runner:
    image: drone/drone-runner-docker:1

    container_name: drone-runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_HOST=drone.barbarisstudio.ru # Изменено на HTTPS
      - DRONE_RPC_PROTO=https
      - DRONE_RPC_SECRET=your_rpc_secret
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=runner
