import type { Metadata } from "next"
import { Montserrat } from "next/font/google"
import "@/globalStyles"
import { Providers } from "@/app/providers/Provider"
import { Header } from "@/widgets/Header"
import { Footer } from "@/widgets/Footer"

const montserrat = Montserrat({
  subsets: ["latin", "cyrillic"],
  display: "swap",
  variable: "--font-montserrat",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} bg-light`}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
